export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const TOGGLE_SHOW_REPOSITORIES = 'TOGGLE_SHOW_REPOSITORIES';
